### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by gedw99** [jkvatne/gio-v#1]
Wrapper the widgets in this way with options makes it quite nice to use gio.
thanks for doing this.

I hit a compile error btw:

```

go run demo.go
go: downloading gioui.org v0.0.0-20210922165522-6665e0ef0fe6
# command-line-arguments
./demo.go:136:83: undefined: app.Pos
./demo.go:139:84: undefined: app.Maximized
./demo.go:142:83: undefined: app.Center
make: *** [run] Error 2

``` 

Not quite sure what the https://github.com/jkvatne/gio-v/blob/main/demo.go#L136 requires. Does it need to use Options maybe ?

**Comment by jkvatne** [comment]
The option functions app.Pos, app Maximized and app.Center is my own extensions to gio. They are found in jkvatne/gio. The plan is to submit a pull-request to get it into the main gio repository. Its just a few extra functions that is convenient on Windows PCs. For now, just coment out the ines 136,139 and 142, or use a replace command in go.mod.

**Comment by gedw99** [comment]
hey @jkvatne 

ah i missed that you were depending on your own gio fork :)

The keyboard based controls looks really good.
