### ISSUE TITLE
hi，has page view widget？

### ISSUE THREAD

**Issue by ddkwork** [jkvatne/gio-v#10]
![R-C.jpg](https://user-images.githubusercontent.com/19886504/204578114-e248e76c-ef6a-41d7-aec3-8042e6c9a8fe.jpg)

**Comment by jkvatne** [comment]
No, but it is quite easy to implement one, using buttons to change pages.

**Comment by ddkwork** [comment]
> No, but it is quite easy to implement one, using buttons to change pages.

cool for you
